version: '3'

services:
  database:
    image: postgres:14.2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentication
    ports:
      - 5432:5432
