database_url := "postgres://user:password@localhost:5432/authentication?sslmode=disable"

test:
  go test ./...

lint:
  staticcheck ./...
  errcheck -ignoretests ./...
  go vet ./...

migrate DIRECTION:
  migrate -path=./authentication/migrations -database={{database_url}} {{DIRECTION}}
